fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.11.0
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
    vcsrepo:
      repo: https://github.com/puppetlabs/puppetlabs-vcsrepo.git
    apache:
      repo: https://github.com/puppetlabs/puppetlabs-apache.git
      ref: 1.10.0
    sudo:
      repo: https://github.com/saz/puppet-sudo.git
  symlinks:
    openondemand: "#{source_dir}"
